# This Action builds the documentation site in mkdocs, and pushes it to the gh-pages branch
# GitHub pages is the BACKUP SITE: https://rcpch.github.io/digital-growth-charts-documentation/
# Azure Statis is the LIVE site https://growth.rcpch.ac.uk/

name: build-and-deploy-to-gh-pages.yml
on:
  push:
    branches:
      - live
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-render-swagger-plugin
      - run: mkdocs gh-deploy --force
